

services:
  postgres:
    image: postgres:latest # Use the latest PostgreSQL image
    container_name: my_postgres_db # Give your container a name
    restart: always # Automatically restart the container if it stops
    environment:
      POSTGRES_USER: angelicaDL # Replace with your PostgreSQL username
      POSTGRES_PASSWORD: Cs360 # Replace with your PostgreSQL password
      POSTGRES_DB: roamfree # Replace with your desired database name
    ports:
      - "5432:5432" # Map port 5432 of the container to port 5432 of the host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data using a named volume

volumes:
  postgres_data: # Define the named volume